logging:
    file:
        name: lotteon.log
        path: /logs
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                org.hibernate.SQL: DEBUG
                org.hibernate.type.descriptor.sql.BasicBinder: TRACE
                org.springframework.jdbc.core: DEBUG
                org.springframework.transaction: DEBUG
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 8080
    servlet:
        context-path: /
spring:

    servlet:
        multipart:
            location: uploads
            max-file-size: 10MB

    mail:
        host: smtp.gmail.com
        port: 587
        username: gardenpark9001@gmail.com
        password: nyux ojpw ydbv hryf
        #username: gyeol000726@gmail.com
        #password: joeikdynwvkggpds
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    application:
        name: lotteon
        version: ${version}
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty123@
        url: jdbc:mysql://43.200.171.152:3306/LotteON
        username: lotteon
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates

